import os, sys
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
from typing import Optional
from typing_extensions import TypedDict, Literal, Annotated
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from langchain_groq import ChatGroq
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages
from langchain.agents import create_agent
from langchain_core.runnables import RunnableConfig
from sentence_transformers import CrossEncoder
from pathlib import Path
from pydantic import BaseModel, Field
import google.generativeai as genai
from dotenv import load_dotenv
load_dotenv()


from transformers import logging as transformers_logging
transformers_logging.set_verbosity_error()
from src.logger.logging import logging
from src.exception.exception_handler import AppException
from utils import get_checkpointer
from ..tools.tools import retriever, tavily_search, news_search, wiki_search, weather_tool, stock_finance_tool
from .prompt import (router_system_prompt, rag_agent_system_prompt, web_agent_prompt,
                    answer_agent_prompt, vision_agent_prompt)


class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    query: str
    route_decision: Literal["rag", "web", "answer", "multimodal", "router", "none"]
    external_kb_meta: dict
    rag_results: str
    web_results: str
    uploaded_image: bool
    image_data: list
    intermediate_query: str


class Task(BaseModel):
    task_id: str
    task_name: str = Field(description="Name of the task")
    assigned_agent: Literal["knowledge", "web", "multimodal", "answer"]
    depends_on: Optional[list[str]] = Field(default_factory=list, description="List of task_ids that this task depends on")
    status: Literal["pending", "completed", "failed"] = "pending"


class SupervisorResponse(BaseModel):
    tasks: list[Task]
    ready_task: list[str]
    next_agent: Literal["knowledge", "web", "multimodal", "answer", "end"]
    task_complete: bool = False
    reasoning: str = Field(description="Reasoning behind selecting the next agent")







class RagVerdict(BaseModel):
    is_sufficient: bool = Field(..., description="True if retrieved information is sufficient to answer the user query, otherwise False")

class AnswerAgentResponse(BaseModel):
    intermediate_query: Optional[str] = Field(None, description="If the agent needs to ask a follow-up question, it will be stored in this variable, otherwise it will be None")
    final_answer: Optional[str] = Field(None, description="The final answer generated by the answer agent. It will be None if the agent needs to ask a follow-up question, otherwise it will contain the answer to the user query")



# Initialize LLMs
router_llm = ChatGroq(model="openai/gpt-oss-120b", temperature=0).with_structured_output(RouteDecission)
rag_agent_llm = ChatGroq(model="openai/gpt-oss-20b", temperature=0).with_structured_output(RagVerdict)
web_agent_llm =  ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0.4)
answer_llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7).with_structured_output(AnswerAgentResponse)
#meta-llama/llama-4-scout-17b-16e-instruct

# load reranker model for retriever tool
reranker_path = Path("models/bge-reranker-base")
reranker = CrossEncoder(str(reranker_path))

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))                            #type: ignore                              
vision_llm = genai.GenerativeModel("gemini-2.5-flash")                          #type: ignore







def supervisor_node(state: AgentState):

    if state.get("intermediate_query") is not None:
        query = state["intermediate_query"]
    else:
        query = str(state["messages"][-1].content)

    uploaded_image = state.get("uploaded_image", False)

    completed_tasks = []

    for task in state.get("tasks", []):
        if task["status"] == "completed":
            completed_tasks.append(task)

    try:
        chat_template = ChatPromptTemplate(
            [
                ("system", router_system_prompt),
                ("human", "uploaded_image: {uploaded_image}\n\nexternal_kb_meta: {external_kb_meta}\n\nQuestion: {query}")
            ],
            input_variables=["external_kb_meta", "uploaded_image", "query"]
        )
    




# Node 1 : ROUTER NODE
def router_node(state: AgentState):
    """
    This node takes in the user query and the external knowledge base metadata (if available) and
    decides which node to route next based on the query.

    If the route is "none", it returns the router LLM gives the reply.
    Otherwise, it returns the query and the route decision.

    Args:
        state (AgentState): The current state of the agent.

    Returns:
        dict: A dictionary containing the route decision and the query.
    """
    
    if state.get("intermediate_query") is not None:
        query = state["intermediate_query"]
    else:
        query = str(state["messages"][-1].content)

    uploaded_image = state.get("uploaded_image", False)
    
    try:
        chat_template = ChatPromptTemplate(
            [
                ("system", router_system_prompt),
                ("human", "uploaded_image: {uploaded_image}\n\nexternal_kb_meta: {external_kb_meta}\n\nQuestion: {query}")
            ],
            input_variables=["external_kb_meta", "uploaded_image", "query"]
        )

        router = chat_template | router_llm 
        response : RouteDecission = router.invoke({"external_kb_meta": state["external_kb_meta"], 
                                                   "uploaded_image": uploaded_image,
                                                   "query": query
                                                    })                                                 # type: ignore

        if response.route=="none" and response.reply is not None:
            return {
                "route_decision": response.route, 
                "response": response.reply, 
                "messages": [AIMessage(content=response.reply)]
            }
    
        return {
            "route_decision": response.route, 
            "query": query
            }
    
    except Exception as e:
        logging.error("Error in the Router node: {e}, exc_info=True")
        raise AppException(e, sys)


# NODE 2 : RAG NODE
def rag_node(state: AgentState):
    """
    This node takes in the user query and the external knowledge base metadata (if available) and
    retrieves relevant documents from the external knowledge base stored in Pinecone database by
    performing RAG search.

    If the retrieval is successful, it then asks the RAG LLM to decide if the retrieved information is sufficient 
    to answer the user query.
    If the information is sufficient, it routes to the "answer" node, otherwise it routes to the "web" node.

    Args:
        state (AgentState): The current state of the agent.

    Returns:
        dict: A dictionary containing the route decision and the rag search retrieved documents.
    """

    docs = retriever.invoke({"query": state.get("query", "None"), 
                             "index_name": state["external_kb_meta"]["topic"], 
                             "reranker": reranker
                            })

    if docs is None:
        return {
            "route_decision": "web",
            "rag_results": "Failed to retrieve documents from knowledge base, Tool NOT AVAILABLE."
        }

    prompt_template = ChatPromptTemplate(
        [
            ("system", rag_agent_system_prompt),
            ("human", "Question: {query}\n\n retrieved_docs: {retreived_docs}")
        ],
        input_variables=["query", "docs"]
    )

    rag = prompt_template | rag_agent_llm
    try:
        verdict: RagVerdict = rag.invoke({"query": state["query"], "retreived_docs": docs})                          # type: ignore
        # Decide next route
        if verdict.is_sufficient:
            return {
                "route_decision": "answer", 
                "rag_results": docs
                }
        else:
            response = f"""Sufficient information is NOT available in the retrieved documents. However, here are the retrieved documents 
            that might be useful for answering the question after performing a web search:\n {docs}"""
            return {
                "route_decision": "web", 
                "rag_results": response
            }
        
    except Exception as e:
        logging.error(f"Error in rag node: {e}", exc_info=True)
        return {
            "rag_results": "Error during RAG search!", 
            "route_decision": "web"
            }


# NODE 3: WEB NODE
def web_node(state: AgentState):
    """
    This node takes in the user query and performs a web search using the tools given.
    After the web search, it always redirects to the answer agent. The web agent is based on ReAct framework.

    Args:
        state (AgentState): The current state of the agent.

    Returns:
        dict: A dictionary containing the web search results and the route decision.
    """

    web_react_agent = create_agent(
        model = web_agent_llm,
        tools = [tavily_search, news_search, wiki_search, weather_tool, stock_finance_tool],
        system_prompt = web_agent_prompt
    )

    config = RunnableConfig({
        "recursion_limit": 10
        })
    
    try:
        response = web_react_agent.invoke(
            {"messages": [{"role": "user", "content": state["query"]}]},
            config=config
        )
        
        return {
            "web_results": response["messages"][-1].content, 
            "route_decision": "answer"
            }
    
    except Exception as e:
        logging.error(f"Error in web node: {e}", exc_info=True)
        return {
            "web_results": "Error during web search!", 
            "route_decision": "answer"
            }


# NODE 4: ANSWER NODE
def answer_node(state: AgentState):
    """
    This node takes in the user query and the results from the RAG and WEB nodes and generates the final answer 
    based on the context and chat history. 
    If the agent determines that it needs to ask a follow-up question, it routes back to the router node.

    Args:
        state (AgentState): The current state of the agent.

    Returns:
        dict: A dictionary containing the final answer and the next route decision.
    """
    rag_results = state.get("rag_results", "None")
    web_results = state.get("web_results", None)
    chat_history = state["messages"][-15:]
    parser = PydanticOutputParser(pydantic_object=AnswerAgentResponse)

    chat_template = ChatPromptTemplate(
    [
        ("system", answer_agent_prompt),
        ("human", "Context: {rag_results}\n\n Web Results: {web_results}\n\n Chat History: {chat_history}\n\n Question: {query}")
    ],
    input_variables=["rag_results", "web_results", "chat_history", "query"],
    partial_variables={"format_instructions": parser.get_format_instructions()}
    )
    
    chain = chat_template | answer_llm 
    try:
        response : AnswerAgentResponse=chain.invoke({"query": state["query"], 
                                                     "rag_results": rag_results, 
                                                     "web_results": web_results, 
                                                     "chat_history": chat_history
                                                    })                                          # type: ignore
        
        if response.intermediate_query is not None:
            next_route = "router"
            return {
                "route_decision": next_route, 
                "intermediate_query": response.intermediate_query
                }
        else:
            return{
                "route_decision": "none", 
                "web_results": [],
                "messages": [AIMessage(content=response.final_answer)]
                }
        
    except Exception as e:
        logging.error(f"Error in answer node: {e}", exc_info=True)
        return {"messages": [AIMessage(content=f"I apologize, but I encountered an error!! Please try again later.")]}
    

# NODE 5: MULTIMODAL NODE
def multimodal_node(state: AgentState):
    try:
        image_data = state.get("image_data", None)

        if image_data is not None:
            response = vision_llm.generate_content([vision_agent_prompt, state["query"], image_data[0]])            # type: ignore
            return {"response": response.text, "messages": [AIMessage(content=response.text)]}
    
    except Exception as e:
        logging.error(f"Error in multimodal node: {e}", exc_info=True)
        return {"messages": [AIMessage(content=f"I apologize, but I encountered an error!! Please try again later.")]}


# CONDITIONAL FUNCTIONS FOR GRAPH EDGES
def from_router(state) -> Literal["rag", "web", "answer", "multimodal", "none"]:        
    """
    This function takes in the current state of the agent and returns the route decision made by the router node.
    If the route decision is 'router', it raises a ValueError as the router node cannot route to itself.
    """
    if state["route_decision"] == "router":
        raise ValueError("route_decision from router node cannot be 'router' again")
    return state["route_decision"]

def after_rag(state) -> Literal["web_agent", "answer_agent"]:
    """
    This function takes in the current state of the agent and returns the next node to be visited after the RAG node.
    If the route decision is 'web', it returns 'web_agent', otherwise it returns 'answer_agent'.
    """
    if state["route_decision"] == "web":
        return "web_agent"
    else:
        return "answer_agent"

def from_answer(state) -> Literal["follow_up", "none"]:
    """
    This function takes in the current state of the agent and returns the next node to be visited after the answer node.
    If the route decision is 'router', it returns 'follow_up', otherwise it returns 'none'.
    """
    if state["route_decision"] == "router":
        return "follow_up"
    else:
        return "none"
    

# BUILD GRAPH WORKFLOW :
graph = StateGraph(AgentState)

graph.add_node("router", router_node)
graph.add_node("rag_agent", rag_node)
graph.add_node("web_agent", web_node)
graph.add_node("answer_agent", answer_node)
graph.add_node("multimodal_agent", multimodal_node)

graph.set_entry_point("router")
graph.add_conditional_edges(
    "router",
    from_router,
    {
        "rag": "rag_agent",
        "web": "web_agent",
        "answer": "answer_agent",
        "multimodal": "multimodal_agent",
        "none": END
    }
)
graph.add_conditional_edges(
    "rag_agent",
    after_rag,
    {
        "web_agent": "web_agent",
        "answer_agent": "answer_agent"
    }
)
graph.add_edge("web_agent", "answer_agent")
graph.add_edge("multimodal_agent", END)
graph.add_conditional_edges(
    "answer_agent",
    from_answer,
    {
        "follow_up": "router",
        "none": END
    })

# FINALIZE AGENT
checkpointer = get_checkpointer()
ai_agent = graph.compile(checkpointer=checkpointer)